version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - ls
  build:
    commands:
      - echo Build started on `date`
      - aws s3 cp index.html s3://entertainment720-test1/index.html
  post_build:
    commands:
      - echo Build completed on `date`

